import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "../redux/ReduxProvider";
import Navbar from "../components/navbar";

export const metadata: Metadata = {
  title: "L'art De Luxe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        <ReduxProvider>
          <Navbar />
          <div className="overflow-x-hidden">{children}</div>
        </ReduxProvider>
      </body>
    </html>
  );
}
